### ISSUE TITLE
Homework review

### ISSUE THREAD

**Issue by adadychanka** [KyzAlexander/HomeWorkReactPart2_3_15.02.22#1]
https://github.com/KyzAlexander/HomeWorkReactPart2_3_15.02.22/blob/d5cc38296f255ba18667a72e5c4914098f002084/src/App.js#L32

Пропс `onChange` принимает обработчик (функцию), а не число. Тут оно может работать, потому что сам компонент обрабатывает таким ситуации, в другом случае это может сломать приложение.

**Comment by KyzAlexander** [comment]
А я то думал, что же туда прокинуть надо
